sudo: required
language: generic
services:
  - docker

before_install:
  -docker build -t truijenk/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true truijenk/docker-react npm run test